const OPS: [Opc; 0x10] = [
    // 0x00
    Opc::Brk(AddressMode::Impl),
    Opc::Ora(AddressMode::IndX),
    Opc::None,
    Opc::None,
    Opc::None,
    Opc::Ora(AddressMode::Zpg),
    Opc::Asl(AddressMode::Zpg),
    Opc::None,
    Opc::Php(AddressMode::Impl),
    Opc::Ora(AddressMode::Imm),
    Opc::Asl(AddressMode::Acc),
    Opc::None,
    Opc::None,
    Opc::Ora(AddressMode::Abs),
    Opc::Asl(AddressMode::Abs),
    Opc::None,
    // 0x10
];

pub enum Opc {
    Adc(AddressMode),
    And(AddressMode),
    Asl(AddressMode),
    Bcc(AddressMode),
    Bcs(AddressMode),
    Beq(AddressMode),
    Bit(AddressMode),
    Bmi(AddressMode),
    Bne(AddressMode),
    Bpl(AddressMode),
    Brk(AddressMode),
    Bvc(AddressMode),
    Bvs(AddressMode),
    Clc(AddressMode),
    Cld(AddressMode),
    Cli(AddressMode),
    Clv(AddressMode),
    Cmp(AddressMode),
    Cpx(AddressMode),
    Cpy(AddressMode),
    Dec(AddressMode),
    Dex(AddressMode),
    Dey(AddressMode),
    Eor(AddressMode),
    Inc(AddressMode),
    Inx(AddressMode),
    Iny(AddressMode),
    Jmp(AddressMode),
    Jsr(AddressMode),
    Lda(AddressMode),
    Ldx(AddressMode),
    Ldy(AddressMode),
    Lsr(AddressMode),
    Nop(AddressMode),
    Ora(AddressMode),
    Pha(AddressMode),
    Php(AddressMode),
    Pla(AddressMode),
    Plp(AddressMode),
    Rol(AddressMode),
    Ror(AddressMode),
    Rti(AddressMode),
    Rts(AddressMode),
    Sbc(AddressMode),
    Sec(AddressMode),
    Sed(AddressMode),
    Sei(AddressMode),
    Sta(AddressMode),
    Stx(AddressMode),
    Sty(AddressMode),
    Tax(AddressMode),
    Tay(AddressMode),
    Tsx(AddressMode),
    Txa(AddressMode),
    Txs(AddressMode),
    Tya(AddressMode),
    None,
}

pub enum AddressMode {
    Acc,
    Abs,
    AbsX,
    AbsY,
    Imm,
    Impl,
    Ind,
    IndX,
    IndY,
    Rel,
    Zpg,
    ZpgX,
    ZpgY,
}

impl AddressMode {
    pub const fn expected_args(&self) -> usize {
        match self {
            AddressMode::Acc => 0,
            AddressMode::Abs => 2,
            AddressMode::AbsX => 2,
            AddressMode::AbsY => 2,
            AddressMode::Imm => 1,
            AddressMode::Impl => 0,
            AddressMode::Ind => 2,
            AddressMode::IndX => 1,
            AddressMode::IndY => 1,
            AddressMode::Rel => 1,
            AddressMode::Zpg => 1,
            AddressMode::ZpgX => 1,
            AddressMode::ZpgY => 1,
        }
    }
}
